version: '3.10'

services:
  quantai-restaurant:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8006:8006"
      - "50061:50061"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    restart: always 